import './style.css';
import './forest.css';
import { mountStudio } from './landscape.js';

const projects = [
 {id:'apac',object:'The monitor',name:'APAC Brand Intelligence',kind:'Independent project · AI & brand research',color:'#405bdd',intro:'From brand conversations to a clearer brief.',description:'A brand intelligence dashboard exploring how consumer conversations can be organised into useful marketing insights. I designed the prototype around manually curated sample data, with a structure that can later connect to AI analysis and real-time information sources.',details:[['The idea','Bring sentiment, conversation themes, supporting quotes and competitor comparisons into one readable workspace.'],['The experience','Explore insights, reveal the original evidence and compare Nike and Adidas discussion samples in a Hong Kong scenario.'],['Project status','A prototype for future AI-assisted analysis and real-time source integration.']],tags:['Information design','Brand insights','Next.js / React'],visual:'dashboard',link:'https://apac-brand-intelligence.vercel.app/',linkLabel:'Open the live project'},
 {id:'city',object:'The city map',name:'City Mood Map',kind:'Independent project · Interactive storytelling',color:'#397869',intro:'One city. Five different ways to feel it.',description:'An interactive portrait of Hong Kong exploring the relationship between urban spaces, emotion and memory. I designed and built the experience with sound, movement, visual fragments and locally saved user choices.',details:[['Five places','Central, Mong Kok, Sham Shui Po, West Kowloon and Kennedy Town each have their own pace, visual language and interactions.'],['The experience','Users explore the city through personal choices and receive a mood profile that becomes a small memory book.'],['Built as','A Next.js and React experience with browser audio, canvas interactions and locally saved choices.']],tags:['Creative media','Interaction design','City narratives'],visual:'city',link:'https://city-mood-map-bxfearless-4693.vercel.app/',linkLabel:'Open City Mood Map'},
 {id:'lulu',object:'The movement corner',name:'Sunday Reset Club',kind:'Independent project · Brand campaign concept',color:'#b72e47',intro:'Make room for movement and connection.',description:'An independent lifestyle campaign concept imagining a Sunday reset for lululemon Hong Kong, centred on “Move. Connect. Belong.” Created privately for portfolio exploration, not as work or internship output.',details:[['The starting point','A campaign response to time pressure, urban stress and the desire for community.'],['The proposal','A 12-page presentation exploring a lifestyle campaign concept and its visual expression.'],['Independent concept','Created independently for portfolio purposes. Not affiliated with or commissioned by lululemon; no campaign performance results are claimed.']],tags:['Campaign concept','Brand storytelling','Visual direction'],visual:'lulu',link:'https://drive.google.com/file/d/18w6K-5GAPj4kMe2G42AzlQhQjVLrPsy4/view?usp=drivesdk',linkLabel:'Open the campaign PDF'},
 {id:'editorial',object:'The newspaper',name:'Stories from the field',kind:'Internship project · Journalism & editorial',color:'#6e5a46',intro:'Start with a question. Find the human story.',description:'A selection of reporting work I participated in during my correspondent internship at Luzhou Daily, Sichuan, in July 2023, developed collaboratively with editors, reporters and photographers.',details:[['My contribution','Participated in topic development, field reporting, interviews, writing and photography under the guidance of the newsroom team.'],['Collaborative reporting','Contributed to stories about local culture, public safety, health and community life, including a feature on the successful artificial breeding of Chinese shad in Luzhou.'],['Selected stories','Collaborative coverage of volunteers making mung-bean soup for street cleaners during a heatwave; a village map supporting forest-fire prevention; and local public-safety reporting.']],tags:['Collaborative reporting','Editorial writing','Fieldwork'],visual:'editorial'},
 {id:'media',object:'The little camera',name:'Culture in motion',kind:'Internship project · Video & social content',color:'#85683e',intro:'Everyday places, local flavours and stories in motion.',description:'Short-form video work from my internship at Luzhou Media Convergence Center in Sichuan. I participated in the full content workflow: collecting source material, selecting useful moments, editing short videos and shaping them for Douyin. The work focused on local life, food, landscapes and everyday cultural experiences.',details:[['My contribution','Collected and organised footage, selected story angles, edited the videos and prepared the final cuts for social-media publication as part of the media-centre team.'],['Editorial focus','Local food and specialities, places to visit, seasonal leisure, city views and small cultural details that make Luzhou feel lived-in.'],['Internship context','This was collaborative professional work produced during my media-centre internship, separate from my independent portfolio projects.']],tags:['素材收集 · Source gathering','Video editing','Douyin content'],visual:'media',links:[['Watch 01','https://v.douyin.com/UA2EW7yNadQ/'],['Watch 02','https://v.douyin.com/RVoGvd2LaZE/'],['Watch 03','https://v.douyin.com/xYJxmaW1ITA/'],['Watch 04','https://v.douyin.com/DVkItcu39K4/'],['Watch 05','https://v.douyin.com/0ibYX4CXrXo/'],['Watch 06','https://v.douyin.com/SJv8CCrOfqA/'],['Watch 07','https://v.douyin.com/q7AFGcOs2Po/']]},
 {id:'moving-images',object:'The film reel',name:'Moving Images',kind:'Independent project · Filming & editing',color:'#b56b55',intro:'Tracing Saint Petersburg through sacred architecture and fine art.',description:'Two short cultural films introducing Fabergé and the Kazan Cathedral in Saint Petersburg. Through considered framing, location detail and a measured editorial rhythm, the videos turn historical subjects into approachable visual stories.',details:[['My contribution','Planned the visual approach, filmed on location, selected takes, edited the sequences and shaped the final pacing and atmosphere.'],['The subjects','The first film explores Fabergé through its refined craftsmanship, history and visual details. The second introduces the architectural presence and cultural significance of the Kazan Cathedral.'],['Creative direction','The project combines observational filming with concise cultural storytelling, using image, movement and sound to guide the viewer through two distinct parts of Saint Petersburg’s visual heritage.']],tags:['Location filming','Video editing','Cultural storytelling'],visual:'media',linkTitle:'Watch the video pieces',links:[['Fabergé','https://youtu.be/gZ7gOQMkCzM?si=vI8-iq8aJyH1cOhw'],['Kazan Cathedral','https://youtu.be/UxTv7kE2SZI?si=ryEi0Y5SH6gbmKzF']]},
 {id:'hanlin',object:'The little message',name:'Stories for WeChat',kind:'Internship project · New media',color:'#6f8f86',intro:'Making culture easy to discover and share.',description:'New-media work completed during my internship at Hanlin Institute in Saint Petersburg in June 2025. I contributed to WeChat articles that introduced readers to Lake Baikal, Sochi and Orthodox Christmas through accessible cultural and travel explainers. The project text is presented in English, translated and edited from the original Russian portfolio notes.',details:[['My role','Selected topics, wrote articles, designed layouts, published WeChat posts and reviewed basic performance data.'],['Editorial focus','Turned cultural and travel research into clear, approachable explainers about the landscapes and customs of Lake Baikal, the nature and history of Sochi, and Orthodox Christmas traditions.'],['Project context','This is professional internship work, separate from my independent projects such as City Mood Map and APAC Brand Intelligence.']],tags:['WeChat operations','Cultural content','Editorial design'],visual:'media',linkTitle:'Selected WeChat articles',links:[['Lake Baikal','https://mp.weixin.qq.com/s/9Tc4VSv4L9el-jwxuav6zA'],['Sochi','https://mp.weixin.qq.com/s/4T94FLvh3I2OhIHqPTMYVQ'],['Orthodox Christmas','https://mp.weixin.qq.com/s/7O_JeXwJ-B89EVl7K58ccA']]},
 {id:'app',object:'The small laptop',name:'MenuUtility',kind:'Independent project · macOS app',color:'#5e6bc3',intro:'A quiet command centre for the everyday Mac.',description:'A local-first macOS menu bar utility for clipboard history, quick notes, shortcuts and focus reminders. I built it with SwiftUI and AppKit for people who move frequently between text, files and focused tasks.',details:[['What it does','Review recent clipboard items with a click or the number keys 1–5; capture auto-saved notes; open frequently used websites and folders; and manage small system actions from the menu bar.'],['Focus and wellbeing','A configurable Pomodoro timer continues while you work in other apps and sends a system notification when the session ends. A background sedentary reminder also nudges you to take regular movement breaks.'],['Built for privacy','Data is stored locally as JSON, with no account, server or cloud database. UserNotifications handles reminders, and Swift Package Manager handles builds and tests.'],['Project status','The current version includes the core features, local persistence, basic error handling and nine core automated tests.']],tags:['SwiftUI','macOS / AppKit','Local-first tools'],visual:'app',link:'/assets/MenuUtilityApp-macOS.zip',linkLabel:'Download MenuUtility for macOS'},
];

// Lead with the strongest Hong Kong-facing interactive work, followed by
// brand intelligence and product-building; keep professional work visible after them.
projects.unshift(projects.splice(1, 1)[0]);
projects.splice(2, 0, projects.splice(6, 1)[0]);

document.querySelector('#app').innerHTML=`
 <header class="site-header"><a href="#" class="identity" aria-label="Zhengwei Zhuo home"><span class="monogram">z<span>.</span></span><span>Zhengwei Zhuo<small>Creative media / Hong Kong</small></span></a><nav aria-label="Main navigation"><button data-about>About me</button><a href="/assets/Zhengwei_Zhuo_Resume.docx" download>Résumé <span>↗</span></a><a class="contact" href="mailto:bxfearless@gmail.com">Let’s talk <span>↗</span></a></nav></header>
 <main><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="intro-note"><span></span>Welcome to my corner of the city</div><h1 id="hero-title">A place for<br>curious things.</h1><p>I’m Zhengwei. I turn stories, places and ideas<br class="desktop-br"> into things you can explore.</p><div class="view-switch" role="group" aria-label="Choose portfolio view"><button class="active" id="studio-view" aria-pressed="true">◈ &nbsp; Explore the studio</button><button id="list-view" aria-pressed="false">☷ &nbsp; Browse projects</button></div></div><div class="side-note"><span>Currently in Hong Kong</span><span>Open to internship opportunities</span></div>
 <div id="studio-wrap"><div id="scene" role="img" aria-label="An interactive 3D studio. Use the project buttons below to open any project."></div><div id="hotspots"></div><div id="scene-loading">Setting the desk…</div><div class="scene-instruction"><span class="cursor-icon">↖</span> A desk full of stories. Click an object to open one.</div><button id="reset-view" title="Reset camera view" aria-label="Reset studio camera">↺</button></div>
 <div id="project-list" hidden></div>
 <div class="hero-bottom"><span>Stories, systems & a little experimentation.</span><span class="location">22.28° N &nbsp; 114.16° E <span>✳</span></span></div></section>
 <section class="index-section" aria-labelledby="index-heading"><div><p class="section-note">A few things on my desk</p><h2 id="index-heading">Different mediums.<br>The same curiosity.</h2></div><div class="quick-projects">${projects.map(p=>`<button data-project="${p.id}"><span class="project-dot" style="background:${p.color}"></span><span>${p.name}<small>${p.kind}</small></span><span>↗</span></button>`).join('')}</div></section></main>
 <footer><span>卓正薇 / Zhengwei Zhuo</span><a href="mailto:bxfearless@gmail.com">bxfearless@gmail.com ↗</a><span>A studio, always in progress.</span></footer>
 <dialog id="project-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Close project">×</button><div id="dialog-content"></div></dialog>`;

function visual(p){
 if(p.visual==='city')return `<div class="project-visual city-visual"><img src="/assets/city.png" alt="Architectural imagery from City Mood Map"><span>How does<br>Hong Kong<br><i>feel to you?</i></span></div>`;
 if(p.visual==='dashboard')return `<div class="project-visual dashboard-visual"><div class="mini-sidebar">apac<span>Overview<br><br>Conversations<br><br>Insights</span></div><div class="mini-dashboard"><small>Brand intelligence prototype</small><h3>Listen. Understand.<br>Find the next idea.</h3><div class="chart">${[42,65,49,89,70,96,80].map((h,i)=>`<i style="height:${h}%;opacity:${.4+i*.09}"></i>`).join('')}</div><span>Consumer conversations → Marketing insights</span></div></div>`;
 if(p.visual==='lulu')return `<div class="project-visual lulu-visual"><small>Independent campaign concept</small><h3>Sunday<br>Reset Club</h3><span>Move. Connect. Belong.</span><div class="orbit"></div></div>`;
 if(p.visual==='editorial')return `<div class="project-visual editorial-visual editorial-photo-visual editorial-title-card"><div><span>From the newsroom</span><h3>Stories<br>from the field.</h3><small>Luzhou Daily · Sichuan · 2023</small></div><b>REPORTING<br>FIELD NOTES<br>04—07 / 2023</b></div>`;
 if(p.visual==='media'){const isWeChat=p.id==='hanlin';const isMoving=p.id==='moving-images';return `<div class="project-visual media-visual ${isMoving?'moving-image-visual':isWeChat?'wechat-visual':'woodland-visual'}"><span class="film-frame">${isMoving?'Moving<br>Images.':isWeChat?'Stories<br>for WeChat.':'Woodland<br>cinema.'}<i>${isMoving?'◉':isWeChat?'✦':'▶'}</i></span><small>${isMoving?'Framing, rhythm & visual studies':isWeChat?'Cultural explainers & editorial stories':'Video, words & everyday lives'}</small></div>`;}
 return `<div class="project-visual app-visual"><div class="app-menu"><span>◉ &nbsp; Your everyday toolkit</span><p>▤ &nbsp; Clipboard</p><p>⌘ &nbsp; Shortcuts</p><p>◷ &nbsp; Take a break</p></div></div>`;
}
document.querySelector('#project-list').innerHTML=projects.map(p=>`<button class="project-tile" data-project="${p.id}">${visual(p)}<span class="tile-caption"><span>${p.name}<small>${p.kind}</small></span><span>↗</span></span></button>`).join('');
// Keep project navigation intact while giving the entrance its woodland story.
document.title='Zhengwei Zhuo — The story garden';
document.querySelector('meta[name="theme-color"]').content='#e8eddc';
document.querySelector('.intro-note').innerHTML='<span></span>A small clearing for stories & ideas';
document.querySelector('#hero-title').innerHTML='Once upon<br>a curious mind.';
document.querySelector('.hero-copy>p').innerHTML='I’m Zhengwei. Welcome to my story garden.<br>There’s a little of my work in everything you find.';
document.querySelector('#studio-view').textContent='❧  Explore the forest';
document.querySelector('.scene-instruction').textContent='Follow your curiosity. Click a little object to find its story.';
document.querySelector('.hero-bottom>span').textContent='Grown from stories. Made with curiosity.';
document.querySelector('.section-note').textContent='Collected along the way';
document.querySelector('#index-heading').innerHTML='Every little thing<br>has a story.';
document.querySelector('footer>span:last-child').textContent='A garden, always growing.';
document.querySelector('#scene').setAttribute('aria-label','An interactive fairy-tale forest with trees, mushrooms, a cottage and a writing desk. Project buttons open the stories.');
const dialog=document.querySelector('dialog');
function openProject(id){const p=projects.find(p=>p.id===id);if(!p)return;const gallery=p.id==='editorial'?`<div class="editorial-gallery"><figure><img src="/assets/internship/luzhou-05.jpg" alt="Luzhou Daily printed page"><figcaption>Printed newspaper page · feature reporting</figcaption></figure><figure><img src="/assets/internship/luzhou-06.jpg" alt="Luzhou Daily fish farming feature"><figcaption>Field reporting · local industry and food culture</figcaption></figure><figure><img src="/assets/internship/luzhou-08.jpg" alt="Luzhou Daily forest fire map feature"><figcaption>Community reporting · forest-fire prevention map</figcaption></figure><figure><img src="/assets/internship/luzhou-01.png" alt="Translated reporting layout screenshot"><figcaption>Digital publication layout · July 2023</figcaption></figure><figure><img src="/assets/internship/luzhou-02.png" alt="Translated forest-fire reporting layout screenshot"><figcaption>Local governance and public-interest reporting</figcaption></figure><figure><img src="/assets/internship/luzhou-03.png" alt="Translated food culture reporting layout screenshot"><figcaption>Food culture and local development reporting</figcaption></figure><figure><img src="/assets/internship/luzhou-04.png" alt="Translated community feature layout screenshot"><figcaption>Community feature · volunteers and neighbourhood life</figcaption></figure></div>`:'';const videoLinks=p.links?.length?`<section class="video-links"><h3>${p.linkTitle||'Selected short videos'}</h3><div>${p.links.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener">${label}<span>↗</span></a>`).join('')}</div></section>`:'';document.querySelector('#dialog-content').innerHTML=`${visual(p)}<div class="case-body"><p class="section-note">${p.kind}</p><h2 id="dialog-title">${p.name}</h2><p class="case-intro">${p.intro}</p><p>${p.description}</p>${gallery}<div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>${p.details.map(([h,t])=>`<section><h3>${h}</h3><p>${t}</p></section>`).join('')}${videoLinks}${p.link?`<a class="case-link" href="${p.link}" target="_blank" rel="noopener">${p.linkLabel} ↗</a>`:''}</div>`;dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)openProject(b.dataset.project);});
document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.querySelector('[data-about]').onclick=()=>{document.querySelector('#dialog-content').innerHTML=`<div class="about-art">卓<span>正薇</span><small>Hong Kong, by way of Saint Petersburg.</small></div><div class="case-body"><p class="section-note">A little about me</p><h2 id="dialog-title">Hi, I’m Zhengwei.</h2><p class="case-intro">Curious about how stories become experiences.</p><p>My background moves between international journalism and creative media. I’ve worked with reporting, short videos and WeChat content, and now explore brand concepts and interactive digital projects.</p><section><h3>Education</h3><p>Creative Media, master’s studies · City University of Hong Kong · Expected June 2027</p><p>International Journalism, undergraduate studies · Saint Petersburg State University · 2022–2026</p></section><section><h3>Let’s make something thoughtful.</h3><p>I’m exploring internship opportunities in content, brand communications and creative media.</p></section><a class="case-link" href="mailto:bxfearless@gmail.com">Get in touch ↗</a><a class="text-link" href="/assets/Zhengwei_Zhuo_Resume.docx" download>Download résumé</a></div>`;dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';};
let studio;
function changeView(list){document.querySelector('#project-list').hidden=!list;document.querySelector('#studio-wrap').hidden=list;for(const [id,active]of [['list-view',list],['studio-view',!list]]){const b=document.getElementById(id);b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}if(!list)studio?.resize();}
document.getElementById('list-view').onclick=()=>changeView(true);document.getElementById('studio-view').onclick=()=>changeView(false);
try{studio=mountStudio(document.getElementById('scene'),document.getElementById('hotspots'),projects,openProject);document.getElementById('scene-loading').hidden=true;document.getElementById('reset-view').onclick=()=>studio.reset();}catch(e){console.error(e);document.getElementById('scene-loading').textContent='The 3D studio is unavailable on this device. Browse the projects below.';changeView(true);document.getElementById('studio-view').disabled=true;}
const destinations={forest:{name:'Forest workshop',icon:'♧',title:'Where ideas take root.',text:'A writing desk in a sunlit clearing. Start with any object.',items:'All seven stories'},pond:{name:'Moonlit pond',icon:'☾',title:'Follow the quieter path.',text:'A glass city, a little sailboat and a lantern beside the water.',items:'City · Video · Campaign'},library:{name:'Mushroom library',icon:'⌂',title:'A home for collected stories.',text:'Open a book, discover a treasure chest, or try the curious little lamp.',items:'Journalism · AI · App'}};
const visited=new Set(['forest']);
Object.assign(destinations.forest,{name:'Forest valley',title:'A valley full of possibilities.',text:'Follow the paths to an observatory, a tiny city, a cinema and a windmill.',items:'Seven landmarks · Seven projects'});
Object.assign(destinations.pond,{name:'Moonlit harbour',title:'Stories across the water.',text:'Explore the memory harbour, story lighthouse and lakeside retreat.',items:'City · Video · Campaign'});
Object.assign(destinations.library,{name:'Storybook village',title:'A village of collected ideas.',text:'Visit the great story library, the insight archive and the inventor’s cottage.',items:'Journalism · AI · App'});
document.querySelector('#hero-title').innerHTML='A world of<br>little discoveries.';
document.querySelector('.hero-copy>p').innerHTML='I’m Zhengwei. Explore my work through<br>the places, stories and ideas that shape it.';
document.querySelector('.intro-note').innerHTML='<span></span>Welcome to my low-poly world';
document.querySelector('#studio-view').textContent='♧  Explore the world';
document.querySelector('.scene-instruction').textContent='Drag to look around · Use + / − to explore closer · Click a landmark to open a project';
if(studio){document.querySelector('#studio-wrap').insertAdjacentHTML('beforeend',`<aside class="destination-card" aria-live="polite"><span id="destination-items">All seven stories</span><h2 id="destination-title">Where ideas take root.</h2><p id="destination-description">A writing desk in a sunlit clearing. Start with any object.</p></aside><nav class="world-map" aria-label="Explore destinations">${Object.entries(destinations).map(([id,d])=>`<button data-world="${id}" aria-pressed="${id==='forest'}"><span>${d.icon}</span><b>${d.name}</b><i aria-hidden="true">${id==='forest'?'●':'○'}</i></button>`).join('')}<small id="exploration-status" aria-live="polite">1 of 3 places explored</small></nav>`);
 document.querySelector('#studio-wrap').insertAdjacentHTML('beforeend','<div class="camera-zoom" role="group" aria-label="Camera zoom"><button id="zoom-in" aria-label="Zoom in">+</button><button id="zoom-out" aria-label="Zoom out">−</button></div>');
 document.getElementById('zoom-in').onclick=()=>studio.zoomBy(1.18);document.getElementById('zoom-out').onclick=()=>studio.zoomBy(1/1.18);
 document.getElementById('destination-title').textContent=destinations.forest.title;document.getElementById('destination-description').textContent=destinations.forest.text;document.getElementById('destination-items').textContent=destinations.forest.items;
 document.querySelectorAll('[data-world]').forEach(button=>button.onclick=()=>{const id=button.dataset.world,d=destinations[id];studio.setWorld(id);document.body.dataset.world=id;visited.add(id);document.getElementById('destination-title').textContent=d.title;document.getElementById('destination-description').textContent=d.text;document.getElementById('destination-items').textContent=d.items;document.getElementById('exploration-status').textContent=`${visited.size} of 3 places explored`;document.querySelectorAll('[data-world]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.world===id));b.querySelector('i').textContent=visited.has(b.dataset.world)?'●':'○';});document.getElementById('scene').setAttribute('aria-label',`${d.name}. ${d.text} Click an object or use the labelled buttons to open a project.`);});
}
